# prettier官方规则文档 https://prettier.io/docs/options
# 1在eslint基础上 安装使用 npm install --save-dev prettier eslint-plugin-prettier eslint-config-prettier
# 2旧版本在.eslintrc.cj文件中 extends数组最下放添加 'plugin:prettier/recommended', // 放在最下边覆盖eslint默认的规则

tabWidth: 2 # 每个缩进级别的空格数
printWidth: 120 # 单行代码最大长度 超过该值则进行换行
semi: false # 语句末尾是否添加分号
singleQuote: true # 是否使用单引号代替双引号
jsxSingleQuote: false # 在JSX 中使用单引号而不是双引号
useTabs: false # 是否使用制表符代替空格，可选值是true（使用制表符）或false（使用空格）
trailingComma: none # 对象或数组最后一个元素后是否加逗号，可选值是"none"（不加逗号）, "es5"（在ES5中有效的地方加逗号） 或 "all"（包括函数参数尾部的逗号）
bracketSpacing: true # 对象字面量的括号间是否加空格，可选值是true（加空格）或false（不加空格）
arrowParens: 'avoid' # 是否总是给箭头函数的参数加上括号，可选值是"avoid"（只在需要时添加括号）或"always"（总是添加括号）
quoteProps: 'as-needed' # 属性名是否使用引号，当有需要时，可选值是"as-needed"（只在必要时加引号）或"consistent"（保持一致性）
endOfLine: 'auto' # 换行符的样式，可选值是"auto"（根据文件中的第一行决定换行符类型）, "lf"（强制使用 LF 作为换行符）, "crlf"（强制使用 CRLF 作为换行符） 或 "cr"（强制使用 CR 作为换行符）

bracketSameLine: false # 将多行 HTML（HTML、JSX、Vue、Angular）元素的 > 放在最后一行的末尾，而不是单独放在下一行（不适用于自关闭元素）。
# jsxBracketSameLine: false # 在JSX中的 '>' 符号是否与标签的最后一行末尾对齐，可选值是true（与标签的最后一行末尾对齐）或false（另起一行）
rangeStart: 0 # 在某个字符处启动格式化（与rangeEnd配合使用），可选值是任意整数
requirePragma: false # 是否需要特殊标记（如 '@format'）才会格式化文件，可选值是true（需要标记）或false（不需要标记）
insertPragma: false # 是否插入特殊标记（如 '@format'）来格式化文件，可选值是true（插入标记）或false（不插入标记）
overrides: [] # 针对某些文件类型的特殊配置，可选值是数组，数组元素是对象
embeddedLanguageFormatting: 'auto' # 是否格式化内嵌的代码语言，可选值是"auto"（自动）， "off"（不格式化内嵌的代码语言）， "on"（始终格式化内嵌的代码语言）
proseWrap: 'preserve' # 是否要换行符折行，可选值是"preserve"（保持原样）, "always"（始终折行）， "never"（从不折行）
htmlWhitespaceSensitivity: 'css' # HTML 空白敏感度
vueIndentScriptAndStyle: true # Vue 文件脚本和样式标签缩进
singleAttributePerLine: false # 在 HTML、Vue 和 JSX 中每行强制执行单个属性。


# objectWrap: collapse # v3.5.0支持 对象包裹 preserve对象保持多行 | collapse 尽可能保持一行
# experimentalTernaries: false #  三元运算符换行 实验性暂不支持
# experimentalOperatorPosition: 'start' # 运算符位置换行前start 或 换行后 end 实验性暂不支持
